// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/2ftimeplc/2fbackend/delivery-1/ports (interfaces: DBPort)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.com/2ftimeplc/2fbackend/delivery-1/internal/constants/models"
)

// MockDBPort is a mock of DBPort interface.
type MockDBPort struct {
	ctrl     *gomock.Controller
	recorder *MockDBPortMockRecorder
}

// MockDBPortMockRecorder is the mock recorder for MockDBPort.
type MockDBPortMockRecorder struct {
	mock *MockDBPort
}

// NewMockDBPort creates a new mock instance.
func NewMockDBPort(ctrl *gomock.Controller) *MockDBPort {
	mock := &MockDBPort{ctrl: ctrl}
	mock.recorder = &MockDBPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBPort) EXPECT() *MockDBPortMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDBPort) Close(arg0 context.Context) models.Errors {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(models.Errors)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBPortMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDBPort)(nil).Close), arg0)
}

// CreateUser mocks base method.
func (m *MockDBPort) CreateUser(arg0 context.Context, arg1 models.User) (models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDBPortMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDBPort)(nil).CreateUser), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockDBPort) DeleteUser(arg0 context.Context, arg1 models.User) models.Errors {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(models.Errors)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockDBPortMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockDBPort)(nil).DeleteUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockDBPort) GetUserByEmail(arg0 context.Context, arg1 string) (models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockDBPortMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockDBPort)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByPhoneNumber mocks base method.
func (m *MockDBPort) GetUserByPhoneNumber(arg0 context.Context, arg1 string) (models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhoneNumber", arg0, arg1)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// GetUserByPhoneNumber indicates an expected call of GetUserByPhoneNumber.
func (mr *MockDBPortMockRecorder) GetUserByPhoneNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhoneNumber", reflect.TypeOf((*MockDBPort)(nil).GetUserByPhoneNumber), arg0, arg1)
}

// GetUsersByFirstName mocks base method.
func (m *MockDBPort) GetUsersByFirstName(arg0 context.Context, arg1 string) ([]models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByFirstName", arg0, arg1)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// GetUsersByFirstName indicates an expected call of GetUsersByFirstName.
func (mr *MockDBPortMockRecorder) GetUsersByFirstName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByFirstName", reflect.TypeOf((*MockDBPort)(nil).GetUsersByFirstName), arg0, arg1)
}

// GetUsersByLastName mocks base method.
func (m *MockDBPort) GetUsersByLastName(arg0 context.Context, arg1 string) ([]models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByLastName", arg0, arg1)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// GetUsersByLastName indicates an expected call of GetUsersByLastName.
func (mr *MockDBPortMockRecorder) GetUsersByLastName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByLastName", reflect.TypeOf((*MockDBPort)(nil).GetUsersByLastName), arg0, arg1)
}

// UpdateUserEmail mocks base method.
func (m *MockDBPort) UpdateUserEmail(arg0 context.Context, arg1 models.User, arg2 string) (models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockDBPortMockRecorder) UpdateUserEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockDBPort)(nil).UpdateUserEmail), arg0, arg1, arg2)
}

// UpdateUserFirstName mocks base method.
func (m *MockDBPort) UpdateUserFirstName(arg0 context.Context, arg1 models.User, arg2 string) (models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserFirstName", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// UpdateUserFirstName indicates an expected call of UpdateUserFirstName.
func (mr *MockDBPortMockRecorder) UpdateUserFirstName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserFirstName", reflect.TypeOf((*MockDBPort)(nil).UpdateUserFirstName), arg0, arg1, arg2)
}

// UpdateUserLastName mocks base method.
func (m *MockDBPort) UpdateUserLastName(arg0 context.Context, arg1 models.User, arg2 string) (models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLastName", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// UpdateUserLastName indicates an expected call of UpdateUserLastName.
func (mr *MockDBPortMockRecorder) UpdateUserLastName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLastName", reflect.TypeOf((*MockDBPort)(nil).UpdateUserLastName), arg0, arg1, arg2)
}

// UpdateUserPassword mocks base method.
func (m *MockDBPort) UpdateUserPassword(arg0 context.Context, arg1 models.User, arg2 string) (models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockDBPortMockRecorder) UpdateUserPassword(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockDBPort)(nil).UpdateUserPassword), arg0, arg1, arg2)
}

// UpdateUserPhoneNumber mocks base method.
func (m *MockDBPort) UpdateUserPhoneNumber(arg0 context.Context, arg1 models.User, arg2 string) (models.User, models.Errors) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPhoneNumber", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(models.Errors)
	return ret0, ret1
}

// UpdateUserPhoneNumber indicates an expected call of UpdateUserPhoneNumber.
func (mr *MockDBPortMockRecorder) UpdateUserPhoneNumber(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPhoneNumber", reflect.TypeOf((*MockDBPort)(nil).UpdateUserPhoneNumber), arg0, arg1, arg2)
}
