// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import ()

type Admin struct {
	ID             int64       `json:"id"`
	AdminAccountID int64 `json:"admin_account_id"`
}

type User struct {
	ID          int64       `json:"id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	PhoneNumber string      `json:"phone_number"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	CreatedAt   string      `json:"created_at"`
	State       int64 `json:"state"`
}

type Vehicle struct {
	ID          int64       `json:"id"`
	DriverID    int64 `json:"driver_id"`
	VehicleType int64 `json:"vehicle_type"`
}

type VehicleServiceType struct {
	ID          int64       `json:"id"`
	VehicleID   int64 `json:"vehicle_id"`
	ServiceName string      `json:"service_name"`
}

type VehicleType struct {
	ID          int64  `json:"id"`
	VehicleName string `json:"vehicle_name"`
}
