// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import ()

type Admin struct {
	ID             int32       `json:"id"`
	AdminAccountID interface{} `json:"admin_account_id"`
}

type User struct {
	ID          int32       `json:"id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	PhoneNumber string      `json:"phone_number"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	CreatedAt   string      `json:"created_at"`
	State       interface{} `json:"state"`
}

type Vehicle struct {
	ID          int32       `json:"id"`
	DriverID    interface{} `json:"driver_id"`
	VehicleType interface{} `json:"vehicle_type"`
}

type VehicleServiceType struct {
	ID          int32       `json:"id"`
	VehicleID   interface{} `json:"vehicle_id"`
	ServiceName string      `json:"service_name"`
}

type VehicleType struct {
	ID          int32  `json:"id"`
	VehicleName string `json:"vehicle_name"`
}
